import { Template, Category } from '@/types/types';
import { NEWS_FEED_SYSTEM_DESIGN_MD } from '@/data/markdown/news-feed-system-design';
import { INFINITE_SCROLL_MD } from '@/data/markdown/infinite-scroll';
import { JS_OUTPUT_CHALLENGES_SNIPPETS } from '@/data/snippets/js-output-challenges';
import { DEBOUNCE_THROTTLE_STARTER_CODE } from '@/data/starter-code/debounce-throttle';
import { TREE_TRAVERSAL_STARTER_CODE } from '@/data/starter-code/tree-traversal';

export const INITIAL_TEMPLATES: Template[] = [
  {
    id: '1',
    name: 'Infinite Scroll Component',
    slug: 'infinite-scroll-component',
    shortDescription: 'Build a performant list that loads data as the user scrolls down.',
    fullDescription: INFINITE_SCROLL_MD,
    imageUrl: 'https://picsum.photos/seed/infinite/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Medium', 'Performance', 'DOM'],
    category: Category.REACT,
    techStack: ['React', 'IntersectionObserver', 'Fetch API'],
    author: 'FrontendMasters',
    createdAt: '2023-10-15',
  },
  {
    id: '9',
    name: 'JS Output Challenges',
    slug: 'js-output-challenges',
    shortDescription: 'Predict the output of tricky JavaScript snippets involving hoisting, closures, and the event loop.',
    fullDescription: 'This collection tests your deep understanding of the JavaScript runtime. You will be presented with snippets of code and asked to predict the console output. These cover topics like Hoisting, Closures, `this` binding, Asynchronous operations, and the Event Loop.',
    imageUrl: 'https://picsum.photos/seed/jspractice/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Tricky', 'Event Loop', 'Closures'],
    category: Category.SNIPPET_PRACTICE,
    techStack: ['JavaScript', 'ES6'],
    author: 'JSNinja',
    createdAt: '2023-12-10',
    snippets: JS_OUTPUT_CHALLENGES_SNIPPETS
  },
  {
    id: '2',
    name: 'Debounce & Throttle',
    slug: 'debounce-throttle',
    shortDescription: 'Implement custom debounce and throttle utility functions from scratch.',
    fullDescription: 'A classic JavaScript challenge. Write your own implementation of debounce and throttle functions. \n\nDebounce: Ensures that a function is not called until a certain amount of time has passed since it was last called.\nThrottle: Ensures that a function is called at most once in a specified time period.',
    imageUrl: 'https://picsum.photos/seed/debounce/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Easy', 'Utilities', 'Logic'],
    category: Category.JAVASCRIPT,
    techStack: ['JavaScript', 'Closures', 'Async'],
    author: 'JSHero',
    createdAt: '2023-11-02',
    starterCode: DEBOUNCE_THROTTLE_STARTER_CODE
  },
  {
    id: '3',
    name: 'E-commerce Product Page',
    slug: 'ecommerce-product-page',
    shortDescription: 'A complete product detail page with image gallery and cart logic.',
    fullDescription: 'This is a comprehensive project. Build a responsive product page that includes an image gallery with thumbnails, size selector, quantity adjustment, and an "Add to Cart" button that updates a global cart state.',
    imageUrl: 'https://picsum.photos/seed/shop/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Take-Home', 'State Management', 'Layout'],
    category: Category.TAKE_HOME,
    techStack: ['React', 'Redux/Context', 'CSS Modules'],
    author: 'InterviewReady',
    createdAt: '2023-09-20',
  },
  {
    id: '4',
    name: 'Nested Comments System',
    slug: 'nested-comments-system',
    shortDescription: 'Recursive component to display threaded comments like Reddit.',
    fullDescription: 'Design a component that renders a tree of comments. Each comment can have replies, and those replies can have replies (n-levels deep). You must handle the recursive rendering efficiently and provide a way to add new replies.',
    imageUrl: 'https://picsum.photos/seed/comments/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Medium', 'Recursion', 'Data Structures'],
    category: Category.REACT,
    techStack: ['React', 'Recursion', 'JSON'],
    author: 'TechLead',
    createdAt: '2023-12-05',
  },
  {
    id: '5',
    name: 'News Feed System Design',
    slug: 'news-feed-system-design',
    shortDescription: 'Design the frontend architecture for a social media feed like Facebook.',
    fullDescription: NEWS_FEED_SYSTEM_DESIGN_MD,
    imageUrl: 'https://picsum.photos/seed/feed/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Hard', 'Architecture', 'Scaling'],
    category: Category.SYSTEM_DESIGN,
    techStack: ['System Design', 'Caching', 'Network'],
    author: 'ArchMaster',
    createdAt: '2023-08-10',
  },
  {
    id: '6',
    name: 'Typeahead Autocomplete',
    slug: 'typeahead-autocomplete',
    shortDescription: 'Search input that suggests results while typing with keyboard navigation.',
    fullDescription: 'Build a reusable Autocomplete component. It should fetch results asynchronously, cache previous queries, bold the matching text in results, and support full keyboard navigation (ArrowUp, ArrowDown, Enter).',
    imageUrl: 'https://picsum.photos/seed/typeahead/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Medium', 'Accessibility', 'Async'],
    category: Category.REACT,
    techStack: ['React', 'Hooks', 'Accessibility'],
    author: 'ComponentLib',
    createdAt: '2023-10-28',
  },
  {
    id: '7',
    name: 'Holy Grail Layout',
    slug: 'holy-grail-layout',
    shortDescription: 'Implement the classic 3-column layout using modern CSS Grid.',
    fullDescription: 'Create the "Holy Grail" layout (Header, Footer, Left Sidebar, Right Sidebar, Center Content) using CSS Grid. Ensure it is fully responsive, collapsing into a single column on mobile devices.',
    imageUrl: 'https://picsum.photos/seed/grid/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Easy', 'CSS Grid', 'Flexbox'],
    category: Category.CSS,
    techStack: ['CSS3', 'Grid', 'Media Queries'],
    author: 'CSSNinja',
    createdAt: '2023-11-15',
  },
  {
    id: '8',
    name: 'Tree Traversal Visualizer',
    slug: 'tree-traversal-visualizer',
    shortDescription: 'Visualize DFS and BFS algorithms on a binary tree DOM structure.',
    fullDescription: 'An algorithmic challenge with a UI twist. Render a binary tree on the screen and create buttons to trigger "Depth First Search" and "Breadth First Search". Highlight the nodes one by one as they are visited.',
    imageUrl: 'https://picsum.photos/seed/tree/800/600',
    demoUrl: '#',
    githubUrl: '#',
    tags: ['Hard', 'Algorithms', 'Animation'],
    category: Category.ALGORITHMS,
    techStack: ['JavaScript', 'DOM Manipulation', 'Algorithms'],
    author: 'AlgoExpert',
    createdAt: '2023-09-01',
    starterCode: TREE_TRAVERSAL_STARTER_CODE
  }
];
